# inventory.ini
[dns]
srv-dns-01 ansible_host=192.168.18.11

[dns2]
srv-dns-02 ansible_host=192.168.18.12

[proxy]
srv-proxy-01 ansible_host=192.168.18.14

[media_private]
srv-media-private ansible_host=192.168.18.13

[media_shared]
srv-media-shared ansible_host=192.168.18.26

[media:children]
media_private
media_shared

[pitwall]
srv-pitwall-01 ansible_host=192.168.18.25

[fitness]
srv-fit-01 ansible_host=192.168.18.27

[gym]
srv-gym-01 ansible_host=192.168.18.28

[all:vars]
ansible_user=devops
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/rafif/.ssh/id_ed25519_homelab
